### ISSUE TITLE
Error and nil pointer exception during central startup phase for Istio-based CVEs

### ISSUE THREAD

**Issue by balpert89** [stackrox/stackrox#3719]
Hi stackrox team,

we are facing an issue where the central is experiencing CrashLoop Backoffs because of a nil pointer exception. The application logs indicate that:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x33b2efd]

goroutine 125 [running]:
github.com/stackrox/rox/central/cve/converter/utils.nvdCvssv2ToProtoCvssv2(0x0)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:173 +0x1d
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEToEmbeddedCVE(0xc011f60f40, 0x1)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:128 +0xb1
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEsToEmbeddedCVEs({0xc011f02160, 0x16, 0x0}, 0x15117)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:219 +0x97
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).updateCVEs(0xc002e16d80, {0xc011f02160, 0x16, 0x16})
	github.com/stackrox/rox/central/cve/fetcher/istio.go:71 +0x45
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).initialize(0xc011ae17a0)
	github.com/stackrox/rox/central/cve/fetcher/istio.go:46 +0xc5
github.com/stackrox/rox/central/cve/fetcher.(*orchestratorIstioCVEManagerImpl).initialize(0xc011af2600)
	github.com/stackrox/rox/central/cve/fetcher/manager_impl.go:58 +0x2ba
github.com/stackrox/rox/central/cve/fetcher.NewOrchestratorIstioCVEManagerImpl({0x73c9450, 0xc00cc28780}, {0x0, 0x0}, {0x7398a80, 0xc011ae16c0}, {0x7379f38, 0xc010c71100}, 0xc012f48540)
	github.com/stackrox/rox/central/cve/fetcher/manager.go:72 +0x372
github.com/stackrox/rox/central/cve/fetcher.SingletonManager.func1()
	github.com/stackrox/rox/central/cve/fetcher/singleton.go:31 +0x1d7
sync.(*Once).doSlow(0xc01503c520, 0xc01503c510)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/stackrox/rox/central/cve/fetcher.SingletonManager()
	github.com/stackrox/rox/central/cve/fetcher/singleton.go:22 +0x55
github.com/stackrox/rox/central/graphql/resolvers.New()
	github.com/stackrox/rox/central/graphql/resolvers/resolver.go:158 +0x95a
github.com/stackrox/rox/central/graphql/handler.Handler()
	github.com/stackrox/rox/central/graphql/handler/handler.go:99 +0xba
main.customRoutes()
	github.com/stackrox/rox/central/main.go:615 +0x89a
main.startGRPCServer()
	github.com/stackrox/rox/central/main.go:487 +0x9cc
created by main.main
	github.com/stackrox/rox/central/main.go:277 +0x3d3
```

Full logs - please note, I have tried to use the newest version `3.72.1`, but the error has happened for `3.72.0` as well:

```
'/usr/local/share/ca-certificates/central.crt' -> '/etc/pki/ca-trust/source/anchors/central.crt'
'/etc/pki/injected-ca-trust/tls-ca-bundle.pem' -> '/etc/pki/ca-trust/source/anchors/tls-ca-bundle.pem'
start-central: 2022/11/07 10:48:04.014453 logger.go:26: Info: Log /var/lib/stackrox/migration_log/log.txt has 3016 lines, truncate it to the last 3000 lines.
Migrator: 2022/11/07 10:48:04.089634 log.go:13: Info: In migrator.run()
pkg/migrations: 2022/11/07 10:48:04.090120 migration_version.go:64: Info: Migration version of database at /var/lib/stackrox/.previous: &{/var/lib/stackrox/.previous 3.72.0 108 0001-01-01 00:00:00 +0000 UTC}
clone/rocksdb: 2022/11/07 10:48:04.090196 db_clone_manager_impl.go:62: Info: Found clone .previous -> .db-e8b80542-6fab-4c66-9c6c-5e5c58af3de5
pkg/migrations: 2022/11/07 10:48:04.090289 migration_version.go:64: Info: Migration version of database at /var/lib/stackrox/current: &{/var/lib/stackrox/current 3.72.1 108 0001-01-01 00:00:00 +0000 UTC}
clone/rocksdb: 2022/11/07 10:48:04.090317 db_clone_manager_impl.go:62: Info: Found clone current -> .db-14562958-7a80-45b2-9aa5-dd41da498247
clone/rocksdb: 2022/11/07 10:48:04.090347 db_clone_manager_impl.go:117: Info: Database clones:
clone/rocksdb: 2022/11/07 10:48:04.090373 db_clone_manager_impl.go:119: Info: .previous -> &{/var/lib/stackrox/.previous 3.72.0 108 0001-01-01 00:00:00 +0000 UTC}
clone/rocksdb: 2022/11/07 10:48:04.090392 db_clone_manager_impl.go:119: Info: current -> &{/var/lib/stackrox/current 3.72.1 108 0001-01-01 00:00:00 +0000 UTC}
Migrator: 2022/11/07 10:48:04.090410 log.go:18: Info: Clone to Migrate "current", ""
Migrator: 2022/11/07 10:48:04.090431 log.go:13: Info: starting DB compaction
Migrator: 2022/11/07 10:48:04.090543 log.go:18: Info: Free fraction of 0.0015 (167936/114982912) is < 0.7500. Will not compact
Migrator: 2022/11/07 10:48:04.115108 log.go:18: Info: In runner.Run
Migrator: 2022/11/07 10:48:04.115360 log.go:18: Info: DB is up to date at version 108. Nothing to do here.
clone/rocksdb: 2022/11/07 10:48:04.117331 db_clone_manager_impl.go:205: Info: Persisting upgraded clone: current
pkg/mtls/certwatch: 2022/11/07 10:48:04.369983 certwatch.go:59: Info: No TLS certificate found. Using internal certificates for HTTPS. Watch dir: "/run/secrets/stackrox.io/default-tls-cert"
main: 2022/11/07 10:48:04.420823 main.go:246: Info: Running StackRox Version: 3.72.1
version: 2022/11/07 10:48:04.445506 ensure.go:55: Info: Version found in the DB was current. We're good to go!
pkg/migrations: 2022/11/07 10:48:04.445795 migration_version.go:64: Info: Migration version of database at /var/lib/stackrox/current: &{/var/lib/stackrox/current 3.72.1 108 0001-01-01 00:00:00 +0000 UTC}
auth/userpass: 2022/11/07 10:48:04.500403 watch_handler.go:38: Info: htpasswd file found. Updating basic auth credentials
auth/userpass: 2022/11/07 10:48:04.551163 watch_handler.go:38: Info: htpasswd file found. Updating basic auth credentials
globaldb/dackbox: 2022/11/07 10:48:04.813773 initialize.go:196: Info: no keys to reindex in bucket: image_vuln
globaldb/dackbox: 2022/11/07 10:48:05.317914 initialize.go:196: Info: no keys to reindex in bucket: comp_to_vuln
globaldb/dackbox: 2022/11/07 10:48:05.816803 initialize.go:196: Info: no keys to reindex in bucket: cluster_to_vuln
globaldb/dackbox: 2022/11/07 10:48:06.316723 initialize.go:196: Info: no keys to reindex in bucket: active_components
globaldb/dackbox: 2022/11/07 10:48:06.817790 initialize.go:196: Info: no keys to reindex in bucket: image_to_comp
globaldb/dackbox: 2022/11/07 10:48:07.316803 initialize.go:196: Info: no keys to reindex in bucket: imageBucket
globaldb/dackbox: 2022/11/07 10:48:07.816882 initialize.go:196: Info: no keys to reindex in bucket: image_component
globaldb/dackbox: 2022/11/07 10:48:08.318849 initialize.go:196: Info: no keys to reindex in bucket: deployments
globaldb/dackbox: 2022/11/07 10:48:08.817530 initialize.go:196: Info: no keys to reindex in bucket: image_to_cve
globaldb/dackbox: 2022/11/07 10:48:09.316709 initialize.go:196: Info: no keys to reindex in bucket: nodes
globaldb/dackbox: 2022/11/07 10:48:09.817798 initialize.go:196: Info: no keys to reindex in bucket: node_to_comp
alert/datastore: 2022/11/07 10:48:10.356166 datastore_impl.go:320: Info: [STARTUP] Determining if alert db/indexer reconciliation is needed
alert/datastore: 2022/11/07 10:48:10.356345 datastore_impl.go:326: Info: [STARTUP] Found 0 Alerts to index
alert/datastore: 2022/11/07 10:48:10.356377 datastore_impl.go:357: Info: [STARTUP] Successfully indexed all out of sync alerts
imageintegration/datastore: 2022/11/07 10:48:10.383156 datastore_impl.go:122: Info: [STARTUP] Found 24 Image Integrations to be indexed
imageintegration/datastore: 2022/11/07 10:48:10.384787 datastore_impl.go:130: Info: [STARTUP] Successfully indexed 24 Image Integrations
risk/datastore: 2022/11/07 10:48:10.424536 datastore_impl.go:34: Info: [STARTUP] Indexing risk
risk/datastore: 2022/11/07 10:48:10.674545 datastore_impl.go:46: Info: [STARTUP] Successfully indexed risk
processbaseline/search: 2022/11/07 10:48:10.815980 searcher_impl.go:40: Info: [STARTUP] Indexing process baselines
processindicator/datastore: 2022/11/07 10:48:10.908865 datastore_impl.go:315: Info: [STARTUP] Determining if process db/indexer reconciliation is needed
processindicator/datastore: 2022/11/07 10:48:10.909028 datastore_impl.go:321: Info: [STARTUP] Found 0 Processes to index
processindicator/datastore: 2022/11/07 10:48:10.909051 datastore_impl.go:349: Info: [STARTUP] Successfully indexed all out of sync processes
namespace/datastore: 2022/11/07 10:48:10.982778 datastore.go:133: Info: [STARTUP] initializing namespaces
namespace/datastore: 2022/11/07 10:48:11.047731 datastore.go:153: Info: [STARTUP] Successfully indexed namespaces
pod/datastore: 2022/11/07 10:48:11.080282 datastore_impl.go:79: Info: [STARTUP] Determining if pod db/indexer reconciliation is needed
pod/datastore: 2022/11/07 10:48:11.080413 datastore_impl.go:86: Info: [STARTUP] Found 0 Pods to index
pod/datastore: 2022/11/07 10:48:11.080432 datastore_impl.go:114: Info: [STARTUP] Successfully indexed all out of sync pods
secret/datastore: 2022/11/07 10:48:11.107915 datastore_impl.go:33: Info: [STARTUP] Indexing secrets
secret/datastore: 2022/11/07 10:48:11.765750 datastore_impl.go:46: Info: [STARTUP] Successfully indexed secrets
serviceaccount/datastore: 2022/11/07 10:48:11.896393 datastore_impl.go:35: Info: [STARTUP] Indexing service accounts
serviceaccount/datastore: 2022/11/07 10:48:12.023927 datastore_impl.go:56: Info: [STARTUP] Successfully indexed 1669 service accounts
rbac/k8srole/datastore: 2022/11/07 10:48:12.024032 datastore_impl.go:38: Info: [STARTUP] Indexing roles
rbac/k8srole/datastore: 2022/11/07 10:48:12.269695 datastore_impl.go:59: Info: [STARTUP] Successfully indexed 2406 roles
rbac/k8srolebinding/datastore: 2022/11/07 10:48:12.342655 datastore_impl.go:37: Info: [STARTUP] Indexing rolebindings
rbac/k8srolebinding/datastore: 2022/11/07 10:48:12.768562 datastore_impl.go:58: Info: [STARTUP] Successfully indexed 2863 rolebindings
policy/store/boltdb: 2022/11/07 10:48:12.967050 store.go:139: Info: Loaded 0 new default Policies
cve/fetcher: 2022/11/07 10:48:13.051521 manager_impl.go:55: Info: successfully copied preloaded CVE istio files to persistent volume: "/var/lib/stackrox/cve/istio"
cve/fetcher: 2022/11/07 10:48:13.051668 orchestrator.go:62: Info: Found 3 clusters to scan for orchestrator vulnerabilities.
cve/fetcher: 2022/11/07 10:48:13.052230 orchestrator.go:237: Info: Successfully fetched 0 Kubernetes CVEs
cve/fetcher: 2022/11/07 10:48:13.052278 orchestrator.go:70: Error: failed to reconcile orchestrator OpenShift CVEs: no orchestrator scanners are integrated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x33b2efd]

goroutine 125 [running]:
github.com/stackrox/rox/central/cve/converter/utils.nvdCvssv2ToProtoCvssv2(0x0)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:173 +0x1d
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEToEmbeddedCVE(0xc011f60f40, 0x1)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:128 +0xb1
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEsToEmbeddedCVEs({0xc011f02160, 0x16, 0x0}, 0x15117)
	github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:219 +0x97
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).updateCVEs(0xc002e16d80, {0xc011f02160, 0x16, 0x16})
	github.com/stackrox/rox/central/cve/fetcher/istio.go:71 +0x45
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).initialize(0xc011ae17a0)
	github.com/stackrox/rox/central/cve/fetcher/istio.go:46 +0xc5
github.com/stackrox/rox/central/cve/fetcher.(*orchestratorIstioCVEManagerImpl).initialize(0xc011af2600)
	github.com/stackrox/rox/central/cve/fetcher/manager_impl.go:58 +0x2ba
github.com/stackrox/rox/central/cve/fetcher.NewOrchestratorIstioCVEManagerImpl({0x73c9450, 0xc00cc28780}, {0x0, 0x0}, {0x7398a80, 0xc011ae16c0}, {0x7379f38, 0xc010c71100}, 0xc012f48540)
	github.com/stackrox/rox/central/cve/fetcher/manager.go:72 +0x372
github.com/stackrox/rox/central/cve/fetcher.SingletonManager.func1()
	github.com/stackrox/rox/central/cve/fetcher/singleton.go:31 +0x1d7
sync.(*Once).doSlow(0xc01503c520, 0xc01503c510)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	sync/once.go:59
github.com/stackrox/rox/central/cve/fetcher.SingletonManager()
	github.com/stackrox/rox/central/cve/fetcher/singleton.go:22 +0x55
github.com/stackrox/rox/central/graphql/resolvers.New()
	github.com/stackrox/rox/central/graphql/resolvers/resolver.go:158 +0x95a
github.com/stackrox/rox/central/graphql/handler.Handler()
	github.com/stackrox/rox/central/graphql/handler/handler.go:99 +0xba
main.customRoutes()
	github.com/stackrox/rox/central/main.go:615 +0x89a
main.startGRPCServer()
	github.com/stackrox/rox/central/main.go:487 +0x9cc
created by main.main
	github.com/stackrox/rox/central/main.go:277 +0x3d3
```

**Comment by balpert89** [comment]
Just saw in another environment the logs indicate successful fetch for istio CVEs

```
cve/fetcher: 2022/10/25 09:52:09.813812 orchestrator.go:237: Info: Successfully fetched 0 Kubernetes CVEs
cve/fetcher: 2022/10/25 09:52:09.813871 orchestrator.go:70: Error: failed to reconcile orchestrator OpenShift CVEs: no orchestrator scanners are integrated
cve/fetcher: 2022/10/25 09:52:09.871893 istio.go:50: Info: successfully fetched 21 istio CVEs
vulnerabilityrequest/datastore: 2022/10/25 09:52:09.892453 datastore_impl.go:52: Info: [STARTUP] Found 0 vulnerability requests to index
vulnerabilityrequest/datastore: 2022/10/25 09:52:09.892538 datastore_impl.go:66: Info: [STARTUP] Successfully indexed all vulnerability requests
cve/fetcher: 2022/10/25 09:52:12.249758 orchestrator.go:62: Info: Found 2 clusters to scan for orchestrator vulnerabilities.
```

Whereas the problematic central has the panic during this step. I will change the description accordingly.

**Comment by janisz** [comment]
It looks like it's related to https://github.com/stackrox/stackrox/issues/3508
Have you tried work-around described in https://github.com/stackrox/stackrox/issues/3503#issuecomment-1285606356

**Comment by balpert89** [comment]
Thanks for the pointer, this solves our issue. Sorry for the duplicate issue :)
