### ISSUE TITLE
Unable to see component details

### ISSUE THREAD

**Issue by imdmahajankanika** [stackrox/stackrox#7464]
Hello,

When I click on component affected by CVE (as shown in below screenshot for **xz-libs**), it redirects to another page and displays below error

**Stackrox version:- 4.1.1 (via helm) on OKD 4.13**

![image](https://github.com/stackrox/stackrox/assets/48632517/d1ac5e4b-fa9f-461e-90ec-37567491173f)

![image](https://github.com/stackrox/stackrox/assets/48632517/28dd7f3f-3224-41a0-a6a6-cfcd31ebd683)

**Error message:-**
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Stack trace:-**
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at c (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:624692)
    at Array.map (<anonymous>)
    at https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:625479
    at Array.reduce (<anonymous>)
    at Object.S [as entityContextToQueryObject] (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:625352)
    at Ia (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:72419)
    at hc (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:205291)
    at sa (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3520417)
    at Gs (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3572717)
    at Tu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3559958)
    at Nu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3559886)
    at Ou (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3559749)
    at bu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3556715)
    at https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3506209
    at t.unstable_runWithPriority (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4365542)
    at qi (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3505986)
    at Yi (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3506154)
    at Gi (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3506089)
    at pu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3554092)
    at Object.enqueueSetState (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3510107)
    at g.setState (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4339894)
    at r.<anonymous> (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4700474)
    at c (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4353618)
    at Generator._invoke (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4353406)
    at Generator.next (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4354043)
    at r (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4450842)
    at s (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4451045)

**Component stack:-**
    at hc (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:204188)
    at Zu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:243446)
    at div
    at d (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/3507.25223266.chunk.js:1:11375)
    at div
    at s (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/3507.25223266.chunk.js:1:10498)
    at https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:66176
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4006407)
    at div
    at https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:1046614
    at div
    at $i (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:1068910)
    at Ji (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:1069518)
    at t.Z (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/8736.375d7bbd.chunk.js:1:19330)
    at div
    at div
    at Pu (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/5158.a2b9a262.chunk.js:1:243661)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4004953)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4005870)
    at wu
    at r (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4700122)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4004953)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4005870)
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:417897)
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4006407)
    at div
    at Li (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4709427)
    at main
    at div
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4664361)
    at div
    at uo (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4727474)
    at co (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4728967)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4004953)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4005870)
    at Ls
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:417897)
    at n (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4006407)
    at f (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:419951)
    at t (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4002290)
    at c (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:889017)
    at i (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:890462)
    at g (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3968901)
    at R (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:4626532)
    at c (https://stackrox-central.apps.outcastv2.davidson-idf.fr/static/js/main.d8139a85.js:2:3966950)

**Comment by kurlov** [comment]
@stackrox/ui please have a look

**Comment by dvail** [comment]
Thanks for the report @imdmahajankanika - we've recently merged [two](https://github.com/stackrox/stackrox/pull/7717) [fixes](https://github.com/stackrox/stackrox/pull/7793) to this area that are in the release pipeline for 4.3
